services:

  db:
    container_name: postgres_container
    image: postgres:alpine3.21
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testuser
      PGDATA: /data/postgres
      POSTGRES_DB: sandbox
    volumes:
      - db_volume:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - virtual_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U testuser -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    ports:
      - "8034:80"
    networks:
      - virtual_network
    restart: unless-stopped

networks:
  virtual_network:
    driver: bridge

volumes:
  db_volume:
  pgadmin_volume:

